project_1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("new/", views.new_page, name="new_page"),
    path("edit/", views.edit_page, name="edit_page"),
    path("save/", views.save_page, name="save_page"),
    path("random/", views.random_page, name="random_page"),
]

project_1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project_1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project_1/wiki/encyclopedia/views.py
from markdown2 import Markdown
from django.shortcuts import render
import random

from . import util

def convert_md_to_html(entry):
    content = util.get_entry(entry)
    markdowner = Markdown()
    if content:
        return markdowner.convert(content)
    else:
        return None


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
        })


def entry(request, entry):
    content_html = convert_md_to_html(entry)
    if content_html:
        return render(request, "encyclopedia/entry.html", {
            "entry": entry,
            "content": content_html,
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "message": f"\"{entry}\" was not found!",
        })


def search(request):
    if request.method == "POST":
        search = request.POST["q"]
        content_html = convert_md_to_html(search)

        if content_html:
            return render(request, "encyclopedia/entry.html", {
                "entry": search,
                "content": content_html,
                })
        
        else:
            suggestions = [entry for entry in util.list_entries() if search.lower() in entry.lower()]
            return render(request, "encyclopedia/error.html", {
                "message": f"\"{search}\" was not found! Did you mean to type...",
                "suggestions": suggestions,
            })


def new_page(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = request.POST["content"]

        if util.get_entry(title):
            return render(request, "encyclopedia/error.html", {
                "message": f"\"{title}\" already exists in the encyclopedia!"
            })
        else:
            util.save_entry(title, content)
            content_html = convert_md_to_html(title)
            return render(request, "encyclopedia/entry.html", {
                "entry": title,
                "content": content_html,
            })
    else:
        return render(request, "encyclopedia/new.html")


def edit_page(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": content,
        })


def save_page(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = request.POST["content"]
        util.save_entry(title, content)
        return render(request, "encyclopedia/entry.html", {
            "entry": title,
            "content": convert_md_to_html(title),
        })


def random_page(request):
    title_random = random.choice(util.list_entries())
    return render(request, "encyclopedia/entry.html", {
        "entry": title_random,
        "content": convert_md_to_html(title_random),
    })

project_1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h2>Edit Page</h2>
    <form action="{% url 'encyclopedia:save_page' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title:</label>
        <input type="text" id="title" name="title" value="{{ title }}">
        <br>
        <label for="content">Markdown Content:</label>
        <br>
        <textarea id="content" name="content" style="height: 60vh;">{{ content }}</textarea>
        <br>
        <input type="submit" value="Save" class="btn btn-primary">
    </form>
{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry }}
{% endblock %}

{% block body %}
    {{ content | safe }}
    
    <form action="{% url 'encyclopedia:edit_page' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ entry }}">
        <input type="submit" value="Edit" class="btn btn-primary">
    </form>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Not Found
{% endblock %}

{% block body %}
    <h2>{{ message }}</h2>
    <ul>
    {% for suggestion in suggestions %}
        <li><a href="{% url 'encyclopedia:entry' entry=suggestion %}">{{ suggestion }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project_1/wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h2>Create New Page</h2>
    <form action="{% url 'encyclopedia:new_page' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title:</label>
        <input type="text" id="title" name="title">
        <br>
        <label for="content">Markdown Content:</label>
        <br>
        <textarea id="content" name="content" style="height: 60vh;"></textarea>
        <br>
        <input type="submit" value="Create" class="btn btn-primary">
    </form>
{% endblock %}